allowBuilds:
  esbuild: true
  lightningcss: true
  onnxruntime-node: true
  protobufjs: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite: "catalog:"
patchedDependencies:
  "@tanstack/form-core@1.33.5": patches/@tanstack__form-core@1.33.5.patch
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
