/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCreateOrganizationRouteImport } from './routes/_app/create-organization'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppOrgSlugIndexRouteImport } from './routes/_app/$orgSlug/index'
import { Route as AppOrgSlugDownloadRouteImport } from './routes/_app/$orgSlug/download'
import { Route as AppOrgSlugSecretRouteImport } from './routes/_app/$orgSlug/secret'
import { Route as AppOrgSlugSettingsRouteImport } from './routes/_app/$orgSlug/settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateOrganizationRoute = AppCreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSlugDownloadRoute = AppOrgSlugDownloadRouteImport.update({
  id: '/$orgSlug/download',
  path: '/$orgSlug/download',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSlugSecretRoute = AppOrgSlugSecretRouteImport.update({
  id: '/$orgSlug/secret',
  path: '/$orgSlug/secret',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSlugSettingsRoute = AppOrgSlugSettingsRouteImport.update({
  id: '/$orgSlug/settings',
  path: '/$orgSlug/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/create-organization': typeof AppCreateOrganizationRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$orgSlug/download': typeof AppOrgSlugDownloadRoute
  '/$orgSlug/secret': typeof AppOrgSlugSecretRoute
  '/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/$orgSlug/': typeof AppOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/create-organization': typeof AppCreateOrganizationRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/$orgSlug/download': typeof AppOrgSlugDownloadRoute
  '/$orgSlug/secret': typeof AppOrgSlugSecretRoute
  '/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/$orgSlug': typeof AppOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/create-organization': typeof AppCreateOrganizationRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$orgSlug/download': typeof AppOrgSlugDownloadRoute
  '/_app/$orgSlug/secret': typeof AppOrgSlugSecretRoute
  '/_app/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/_app/$orgSlug/': typeof AppOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/sign-in'
    | '/sign-up'
    | '/$orgSlug/download'
    | '/$orgSlug/secret'
    | '/$orgSlug/settings'
    | '/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-organization'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/$orgSlug/download'
    | '/$orgSlug/secret'
    | '/$orgSlug/settings'
    | '/$orgSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/create-organization'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/$orgSlug/download'
    | '/_app/$orgSlug/secret'
    | '/_app/$orgSlug/settings'
    | '/_app/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-organization': {
      id: '/_app/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AppCreateOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$orgSlug/': {
      id: '/_app/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgSlug/download': {
      id: '/_app/$orgSlug/download'
      path: '/$orgSlug/download'
      fullPath: '/$orgSlug/download'
      preLoaderRoute: typeof AppOrgSlugDownloadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgSlug/secret': {
      id: '/_app/$orgSlug/secret'
      path: '/$orgSlug/secret'
      fullPath: '/$orgSlug/secret'
      preLoaderRoute: typeof AppOrgSlugSecretRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgSlug/settings': {
      id: '/_app/$orgSlug/settings'
      path: '/$orgSlug/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AppOrgSlugSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreateOrganizationRoute: typeof AppCreateOrganizationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrgSlugDownloadRoute: typeof AppOrgSlugDownloadRoute
  AppOrgSlugSecretRoute: typeof AppOrgSlugSecretRoute
  AppOrgSlugSettingsRoute: typeof AppOrgSlugSettingsRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateOrganizationRoute: AppCreateOrganizationRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrgSlugDownloadRoute: AppOrgSlugDownloadRoute,
  AppOrgSlugSecretRoute: AppOrgSlugSecretRoute,
  AppOrgSlugSettingsRoute: AppOrgSlugSettingsRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
